### ISSUE TITLE
ctrl-c causes python interpreter to crash

### ISSUE THREAD

**Issue by gdb** [openai/gym-doom#3] opened 2016-05-08 06:10 UTC
```
>>> import gym, gym_doom; gym.make('DoomCorridor-v0')
[2016-05-07 23:09:35,366] Making new env: DoomCorridor-v0
ViZDoom 1.0.0 (ZDOOM 2.8.1) - Cocoa version
Compiled on May  7 2016

M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding /usr/local/lib/python2.7/site-packages/doom_py/bin/vizdoom.pk3, 583 lumps
 adding /usr/local/lib/python2.7/site-packages/doom_py/scenarios/freedoom2.wad, 3329 lumps
 adding /usr/local/lib/python2.7/site-packages/doom_py/scenarios/deadly_corridor.wad, 7 lumps
vizdoom_controlled is write protected.
vizdoom_instance_id is write protected.
<gym_doom.doom_corridor.DoomCorridorEnv object at 0x10b4ea290>
<CTRL-C here>
>>> libc++abi.dylib: terminating with uncaught exception of type boost::system::system_error: in file '/private/var/folders/tl/1p6_zyn50q79grgz1_984r5w0000gn/T/pip-build-fSdaK7/doom-py/doom_py/vizdoom_api_src/boost/process/posix/wait_for_exit.hpp', line 30: waitpid(2) failed: No child processes
```

Maybe we should block signals in the vizdoom subprocess (is that what's erroring?)? cc/ @ppaquette

**Comment by ppaquette** [comment] 2016-05-08 19:38
Cannot reproduce.

Here is the output I get:

(.env2)philip@philip-Vostro-230:/www/ppaquette/gym-doom$ python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym, gym_doom; env = gym.make('DoomCorridor-v0')
[2016-05-08 15:38:30,046] Making new env: DoomCorridor-v0
>>> print 'Typing Ctrl-C'
Typing Ctrl-C
>>> 
(.env2)philip@philip-Vostro-230:/www/ppaquette/gym-doom$

**Comment by jietang** [comment] 2016-05-18 00:52
I can reproduce this on mac sporadically. Ctrl-C has to happen while VizDoom is initializing.

One of the crashes is related to https://github.com/Marqt/ViZDoom/issues/58 and is fixed by this commit in VizDoom: https://github.com/Marqt/ViZDoom/commit/7218854884278bf046f8f922aed9793624514577

We should consider pulling in the latest VizDoom for this (I think it will be hard to cherry pick because they recently reorganized their repo)

After fixing that issue a different segfault shows up - I spent a couple hours trying to track it down but couldn't quite isolate it - best guess is that it has to do with using a boost ipc message queue from multiple threads when you quit during init(). Might not be worth fixing this unless we start seeing it a lot in practice.

**Comment by jietang** [comment] 2016-05-18 23:16
Repulled the latest vizdoom into doom_py, which fixes the original issue.

**Closed by jietang** 2016-05-18 23:16 UTC
