### ISSUE TITLE
Render window pops up upon env initialization

### ISSUE THREAD

**Issue by gdb** [openai/gym-doom#1] opened 2016-05-08 06:00 UTC
i.e. just run

```>>> import gym, gym_doom; gym.make('DoomCorridor-v0')```

And you'll get a window.

@ppaquette any idea why that is / if it's necessary?

**Comment by ppaquette** [comment] 2016-05-08 19:45
Cannot reproduce

Here is what I get:

```
(.env2)philip@philip-Vostro-230:/www/ppaquette/gym-doom$ python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym, gym_doom; env = gym.make('DoomCorridor-v0')
[2016-05-08 15:44:09,233] Making new env: DoomCorridor-v0
>>> env
<gym_doom.doom_corridor.DoomCorridorEnv object at 0x7fc9738c8290>
>>> ob = env.reset()
>>> env.render()
>>> print 'Window only appears after render() is called.'
Window only appears after render() is called.
>>> 
(.env2)philip@philip-Vostro-230:/www/ppaquette/gym-doom$ 
```

**Comment by gdb** [comment] 2016-05-08 19:48
Oh interesting. I'm running everything on Mac. Will dig in.

**Comment by ppaquette** [comment] 2016-05-08 19:54
The window is opened if:

1) game.set_window_visible(True) is set and an episode is started with game.new_episode(). All environments set the window_visible to False in the __init__ method., or
2) render() is called with mode='human'

**Comment by jietang** [comment] 2016-05-16 18:57
This should be fixed by https://github.com/openai/doom-py/pull/2

**Comment by jietang** [comment] 2016-05-16 22:41
Merged: https://github.com/openai/doom-py/commit/3ba68a08a77f227c9d0f43f5fb582e0756c70ad6

**Closed by jietang** 2016-05-16 22:41 UTC
